### ISSUE TITLE
Update linting for JS  in order to follow a standard convention in the commas

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/web-app#87]
**Steps to reproduce and a minimal demo of the problem**

Try to lint a code like: 

``` js
var obj = {
 a: 'value',
 c: 'another_value', 
}
```

**Current behavior**

It triggers a lint error since does not require the last comma, however this pattern is allowed on the [WP Code Standard](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation).

> Note the comma after the last array item: this is recommended because it makes it easier to change the order of the array, and makes for cleaner diffs when new items are added. 

**Expected/desired behavior**

Always require the last comma on the `object` / `array` that aren't in a single line.

**Other information**

N / A

**Comment by Rulox** [comment]
I only see one problem with this. All JS code will be without the last comma (ie if we use APIs and stuff) The comma in the last element of the JSON/object it's only a PHP or WP convention.

I really don't see the reason to switch, we can have different conventions here... they're actually different languages! :P

**Comment by mitogh** [comment]
- I don't get your first point, would you mind clarify that.
- This is in order to have a consistency between style guides in the languages.  So if you work in either JS or PHP you are going to follow the same style guides.

**Comment by Rulox** [comment]
Yeah sorry. I mean, that we're going to use that comma because it's a php thing in our javascript code..Which to me does not make any sense. 

Probably my first example was not accurate, but are you really sure there's no issues if we do that? For example:

`Ref`: http://stackoverflow.com/questions/5139205/javascript-can-a-comma-occur-after-the-last-set-of-values-in-an-array 

We have FE separated from the BE and they're different languages, I think we have to follow their own code standards as much as we can. I don't see the point of change this in JS only because PHP needs it.

But again, this is a complete personal opinion! I just felt that I had something to add here hehe.

Thank you!

**Comment by mitogh** [comment]
OK I see your point now.
- It's not a PHP thing it's a WordPress Code Standard Rule as mentioned above. And having a one set of rules across languages (were is possible) regardless of the language makes more sense for example if you are going to switch from writting the BE and the FE imagine you have 3 different rules for 3 different languages like: 

```
// valid only PHP
class a   {
}

// Valid only  on JS
class a 
{ 
}

// Valid only on CSS 
.class{
}
```

If you are going to work in any bug on the app you require to know 3 different style guides and if we follow this pattern we need to know `n` style guides as languages.

In my opinion is easier to know one styleguide regardless of the language that you can apply to any part of the site, makes things more consistent and also easier to move around without the pain of learning curve of different style guides.
- For the second point: 
1. The problem is only present on IE 8 and below. 
2. The build process (minification) before the deploy to staging / production deploy removes this since does not have any value on the code example: 

**Before**

``` js
angular
  .module( 'app', [
    'ngConstants',
    'ngSanitize',
    'templateCache',
    'lnCms',
    'lnFilters',
    'lnPatterns', // notice a coma here
  ])
  .config( appConfig )
  .run( appRun );
```

**After build**

``` js
l["default"].module("app", ["ngConstants", "ngSanitize", "templateCache", "lnCms", "lnFilters", "lnPatterns"]).config(o).run(r);

// Notice there is no comma above.
```

As you can see I don't see any reason to avoid the implementation of this new rule.

**Comment by Rulox** [comment]
Yeah, WP standard sorry about that! :+1: 

I just think that we should follow the community standards on every language as much as we can, also because we're developing Open Source tools, and maybe people will use these standards if they want to contribute, but we're setting different rules only because we want some consistency.

About the minification thing, you're right, I didn't notice that before.

I see your points, and I think they're valid points. I still don't think this is something needed. Anyways, let's go with the change! If everyone agrees I don't see the reason to delay this.

Thanks you.

**Comment by mitogh** [comment]
Sounds good, just as a heads up, we are already doing this with JS and Sass where we are following specific rules for the JS that match the WP Standard Guide  + The John Papa Style guide.

**Comment by camilodelvasto** [comment]
Though initially I was also reluctant to the idea of a trailing comma in an array (for the same reasons @Rulox exposed before), I can see as well the advantages: quick copy/paste for sorting elements in an array, better diffs and general consistency across project environments.... and besides, so I think it makes sense to go for it @mitogh ;)
